str = "hello, sites"
siteConfig =  {
    "www.google.com": "[data-tab_type='LIVE_COMMENTS']",
    "www.linkedin.com": "[data-control-name='comments_count'], .feed-shared-update__comments-container, .feed-shared-update-v2__comments-container, .feed-shared-first-prompt-block, .comment, li.social-details-social-counts__comments",
    "www.msn.com": "i[aria-label='Open replies'], [class*='commentContainer'], [class*='commentOverlayContainer'], [aria-label^='Comments'], .comments-count-button, a[part='comments-count-button']",
    "myanimelist.net": "div.information > p.info > a:nth-child(2), .news-info-block .comment, .comment-list, .comment-list + .mt16",
    "n4g.com": ".comments-container-outer, .sd-commentcount",
    "www.namecheap.com": ".sds-blog-card__info-comments, .sds-blog-post__comments, #comments, #toggle-comments",
    "news.ycombinator.com": ".comment-tree",
    "nypost.com": "#nypost-openweb-conversation, .comments-inline-cta, button[aria-label='Comments']",
    "www.o2.pl": "div[data-st-area='st-article-reactions'] > div:nth-child(1) > div:nth-child(1) > div:nth-child(1), div[data-st-area='st-article'] > div:nth-child(3) > div:nth-child(1) > div:nth-child(2)",
    "www.pinterest.com": "[data-test-id='canonical-card']",
    "www.reddit.com": "[data-testid='post-container']~div, .icon-comment, .icon-comment~span",
    "old.reddit.com": ".commentarea, a[data-event-action='comments']",
    "slickdeals.net": "#commentsBox, #joinTheConversationBox, .add-comment, .add-comment + span, a[href='#commentsBox']",
    "soundcloud.com": "div.commentForm, div.commentsList, li[title$='comments']",
    "stackexchange.com": ".comments, .comments-link, .js-link-separator",
    "stackoverflow.com": ".comments, .comments-link, .js-link-separator",
    "superuser.com": ".comments, .comments-link, .js-link-separator",
    "www.techdirt.com": ".storylinks, .comments",
    "www.tiktok.com": "[data-e2e$='comment-icon'], [data-e2e$='comment-count'], [class*='DivCommentListContainer'], [class*='DivBottomCommentContainer']",
    "tweakers.net": "#reacties, #articleMeta .commentCount",
    "twitter.com": "[data-testid='reply'], [aria-label='Timeline: Conversation'] > div > div > div:not(:first-child), [aria-label='Timeline: Conversation'] > div > div:not(:first-child)",
    "www.vijesti.me": ".dataComments, .artViews > span:nth-child(3), .commWrap",
    "vk.com": ".replies, .post_replies_header, .wl_replies_wrap, .wl_reply_form_wrap, #pv_comments",
    "www.washingtonpost.com": ".comments-btn, .comments, a[href='#comments-wrapper'], #comments-wrapper",
    "www.watson.ch": ".comments_count, .share-go-to-discussion, [class^='watson-discussion'], .standard.comments",
    "www.wdwmagic.com": "#Body_Panel_Conversation, div[id^='Body_RepeaterForumPosts_Panel_ForumPost_'], a[id^='Body_HyperLink_ViewComments']",
    "www.wykop.pl": "div.grid-main div.fix-b-border, div.grid-main > ul.comments-stream, div.grid-main > div:not(:first-child)",
    "wiadomosci.gazeta.pl": "#commentsApp",
    "www.yahoo.com": "div[id$='Comments'], div.caas-share-buttons > a:nth-child(1), #spotIm-conversations-module-wrapper, div[id$='spotim-wrapper']",
    "news.yahoo.com": "div[id$='Comments'], div.caas-share-buttons > a:nth-child(1), #spotIm-conversations-module-wrapper, div[id$='spotim-wrapper']",
    "www.youtube.com": "#comment-teaser, #comments",
    "wydarzenia.interia.pl": "a.is-comment, #commentsZoneList, div.comments-placeholder"
}